basePath: /v1
consumes:
- application/json
definitions:
  Ping:
    description: Product Product Product Product defines the structure for an API
      product
    properties:
      name:
        type: string
        x-go-name: Name
    type: object
    x-go-package: doc-generation/request
host: localhost
info:
  contact:
    email: khemraj.meena@khetipoint.com
    name: Khem Raj
  description: |-
    the purpose of this application is to provide an application
    that is using plain go code to define an API

    This should demonstrate all the possible comment annotations
    that are available to turn go code into a fully compliant swagger 2.0 spec
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
  termsOfService: there are no TOS at this moment, use at your own risk we take no
    responsibility
  title: Doc generation sample api.
  version: 0.0.1
paths:
  /ping-check:
    get:
      consumes:
      - application/json
      description: This will return hello msg to user
      operationId: ping
      produces:
      - application/json
      responses:
        "200":
          $ref: '#/responses/Ping'
      schemes:
      - http
      - https
      summary: Hello msg from server
produces:
- application/json
responses:
  Ping:
    description: Product Product Product Product defines the structure for an API
      product
    headers:
      name:
        type: string
schemes:
- http
- https
security:
- api_key: []
securityDefinitions:
  api_key:
    in: header
    name: KEY
    type: apiKey
  oauth2:
    authorizationUrl: /oauth2/auth
    flow: accessCode
    in: header
    scopes:
      bar: foo
    tokenUrl: /oauth2/token
    type: oauth2
swagger: "2.0"
x-meta-array:
- value1
- value2
x-meta-array-obj:
- name: obj
  value: field
x-meta-value: value
